-- MySQL Script generated by MySQL Workbench
-- Sun Jul 16 13:25:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shs_library_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shs_library_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shs_library_db` DEFAULT CHARACTER SET latin1 ;
USE `shs_library_db` ;

-- -----------------------------------------------------
-- Table `shs_library_db`.`PublicationType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`PublicationType` (
  `PublicationTypeId` INT NOT NULL AUTO_INCREMENT,
  `PublicationType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PublicationTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Status` (
  `StatusId` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Publication` (
  `PublicationId` INT NOT NULL AUTO_INCREMENT,
  `PublicationTypeId` INT NOT NULL,
  `StatusId` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Year` INT NOT NULL,
  `BorrowedUntil` DATETIME NULL,
  `ReservedUntil` DATETIME NULL,
  `ImageLocation` VARCHAR(100) NOT NULL
  PRIMARY KEY (`PublicationId`),
  INDEX `fk_Publication_PublicationType1_idx` (`PublicationTypeId` ASC),
  INDEX `fk_Publication_Status1_idx` (`StatusId` ASC),
  CONSTRAINT `fk_Publication_PublicationType1`
    FOREIGN KEY (`PublicationTypeId`)
    REFERENCES `shs_library_db`.`PublicationType` (`PublicationTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publication_Status1`
    FOREIGN KEY (`StatusId`)
    REFERENCES `shs_library_db`.`Status` (`StatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Author` (
  `AuthorId` INT NOT NULL,
  `AuthorFirstName` VARCHAR(45) NOT NULL,
  `AuthorLastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AuthorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Publisher` (
  `PublisherId` INT NOT NULL AUTO_INCREMENT,
  `Publisher` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PublisherId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Tags` (
  `TagId` INT NOT NULL AUTO_INCREMENT,
  `Tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TagId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`SecurityQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`SecurityQuestion` (
  `SecurityQuestionId` INT NOT NULL AUTO_INCREMENT,
  `SecurityQuestio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SecurityQuestionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Privilege` (
  `PrivilegeId` INT NOT NULL AUTO_INCREMENT,
  `Privilege` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PrivilegeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `MiddleInitial` VARCHAR(2) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `PasswordHash` BINARY(64) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `IdentificationNumber` VARCHAR(45) NOT NULL,
  `SecurityQuestionId` INT NOT NULL,
  `AnswerHash` BINARY(64) NOT NULL,
  `Privilege_PrivilegeId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `fk_User_SecurityQuestion1_idx` (`SecurityQuestionId` ASC),
  INDEX `fk_User_Privilege1_idx` (`Privilege_PrivilegeId` ASC),
  CONSTRAINT `fk_User_SecurityQuestion1`
    FOREIGN KEY (`SecurityQuestionId`)
    REFERENCES `shs_library_db`.`SecurityQuestion` (`SecurityQuestionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Privilege1`
    FOREIGN KEY (`Privilege_PrivilegeId`)
    REFERENCES `shs_library_db`.`Privilege` (`PrivilegeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`PublicationTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`PublicationTransaction` (
  `PublicationTransactionId` INT NOT NULL AUTO_INCREMENT,
  `PublicationTransactionDateTime` DATETIME NOT NULL,
  `UserId` INT NOT NULL,
  `PublicationId` INT NOT NULL,
  `DateBorrowed` DATETIME NULL,
  `DateReturned` DATETIME NULL,
  PRIMARY KEY (`PublicationTransactionId`),
  INDEX `fk_PublicationTransaction_User1_idx` (`UserId` ASC),
  INDEX `fk_PublicationTransaction_Publication1_idx` (`PublicationId` ASC),
  CONSTRAINT `fk_PublicationTransaction_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `shs_library_db`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PublicationTransaction_Publication1`
    FOREIGN KEY (`PublicationId`)
    REFERENCES `shs_library_db`.`Publication` (`PublicationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Reviews` (
  `ReviewId` INT NOT NULL AUTO_INCREMENT,
  `Review` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ReviewId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`Room` (
  `RoomId` INT NOT NULL AUTO_INCREMENT,
  `Capacity` INT NOT NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`RoomId`),
  INDEX `fk_Room_Status1_idx` (`Status` ASC),
  CONSTRAINT `fk_Room_Status1`
    FOREIGN KEY (`Status`)
    REFERENCES `shs_library_db`.`Status` (`StatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`RoomSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`RoomSlot` (
  `RoomSlotId` INT NOT NULL,
  `StartTime` TIME(0) NOT NULL,
  `EndTime` TIME(0) NOT NULL,
  PRIMARY KEY (`RoomSlotId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`RoomTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`RoomTransaction` (
  `RoomTransactionId` INT NOT NULL AUTO_INCREMENT,
  `RoomTransactionDateTime` DATETIME NOT NULL,
  `User_UserId` INT NOT NULL,
  `Room_RoomId` INT NOT NULL,
  `RoomSlotId` INT NOT NULL,
  `RoomReserveDate` DATE NOT NULL,
  PRIMARY KEY (`RoomTransactionId`),
  INDEX `fk_RoomTransaction_User1_idx` (`User_UserId` ASC),
  INDEX `fk_RoomTransaction_Room1_idx` (`Room_RoomId` ASC),
  INDEX `fk_RoomTransaction_RoomSlot1_idx` (`RoomSlotId` ASC),
  CONSTRAINT `fk_RoomTransaction_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `shs_library_db`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoomTransaction_Room1`
    FOREIGN KEY (`Room_RoomId`)
    REFERENCES `shs_library_db`.`Room` (`RoomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoomTransaction_RoomSlot1`
    FOREIGN KEY (`RoomSlotId`)
    REFERENCES `shs_library_db`.`RoomSlot` (`RoomSlotId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`AuthorPublication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`AuthorPublication` (
  `AuthorId` INT NOT NULL,
  `PublicationId` INT NOT NULL,
  PRIMARY KEY (`AuthorId`, `PublicationId`),
  INDEX `fk_Publication_has_Author_Author1_idx` (`AuthorId` ASC),
  INDEX `fk_Publication_has_Author_Publication_idx` (`PublicationId` ASC),
  CONSTRAINT `fk_Publication_has_Author_Publication`
    FOREIGN KEY (`PublicationId`)
    REFERENCES `shs_library_db`.`Publication` (`PublicationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publication_has_Author_Author1`
    FOREIGN KEY (`AuthorId`)
    REFERENCES `shs_library_db`.`Author` (`AuthorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`PublisherPublications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`PublisherPublications` (
  `PublisherId` INT NOT NULL,
  `PublicationId` INT NOT NULL,
  PRIMARY KEY (`PublisherId`, `PublicationId`),
  INDEX `fk_Publisher_has_Publication_Publication1_idx` (`PublicationId` ASC),
  INDEX `fk_Publisher_has_Publication_Publisher1_idx` (`PublisherId` ASC),
  CONSTRAINT `fk_Publisher_has_Publication_Publisher1`
    FOREIGN KEY (`PublisherId`)
    REFERENCES `shs_library_db`.`Publisher` (`PublisherId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publisher_has_Publication_Publication1`
    FOREIGN KEY (`PublicationId`)
    REFERENCES `shs_library_db`.`Publication` (`PublicationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`PublicationTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`PublicationTags` (
  `PublicationId` INT NOT NULL,
  `TagId` INT NOT NULL,
  PRIMARY KEY (`PublicationId`, `TagId`),
  INDEX `fk_Tags_has_Publication_Publication1_idx` (`PublicationId` ASC),
  INDEX `fk_Tags_has_Publication_Tags1_idx` (`TagId` ASC),
  CONSTRAINT `fk_Tags_has_Publication_Tags1`
    FOREIGN KEY (`TagId`)
    REFERENCES `shs_library_db`.`Tags` (`TagId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_Publication_Publication1`
    FOREIGN KEY (`PublicationId`)
    REFERENCES `shs_library_db`.`Publication` (`PublicationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shs_library_db`.`PublicationReviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shs_library_db`.`PublicationReviews` (
  `Publication_PublicationId` INT NOT NULL,
  `Reviews_ReviewId` INT NOT NULL,
  PRIMARY KEY (`Publication_PublicationId`, `Reviews_ReviewId`),
  INDEX `fk_Reviews_has_Publication_Publication1_idx` (`Publication_PublicationId` ASC),
  INDEX `fk_Reviews_has_Publication_Reviews1_idx` (`Reviews_ReviewId` ASC),
  CONSTRAINT `fk_Reviews_has_Publication_Reviews1`
    FOREIGN KEY (`Reviews_ReviewId`)
    REFERENCES `shs_library_db`.`Reviews` (`ReviewId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_has_Publication_Publication1`
    FOREIGN KEY (`Publication_PublicationId`)
    REFERENCES `shs_library_db`.`Publication` (`PublicationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
